Problems api, database setup, fixed husky problems
Tamas-Leung/CodeChamp pull request #59
Opened 2022-11-07 23:23 UTC by Tamas-Leung

2022-11-07 23:26 UTC, AntonKanug commented
closes #19 
closes #20

2022-11-07 23:27 UTC, AntonKanug approved these changes

2022-11-08 00:19 UTC, YoussefRizkalla requested changes

2022-11-08 00:19 UTC, YoussefRizkalla commented on src/backend/src/database/mongoose.js
> +const ProblemSchema = new Schema({
Have the schemas in a different file and import them

2022-11-08 00:19 UTC, YoussefRizkalla commented on src/backend/src/database/mongoose.js
> +const ProblemType = {
Include in same file as schema

2022-11-08 00:19 UTC, YoussefRizkalla commented on src/backend/src/database/mongoose.js
> +const ProblemDifficulty = {
Include in same file as schema

2022-11-08 00:32 UTC, YoussefRizkalla approved these changes

2022-11-08 00:36 UTC, dipesube approved these changes

2022-11-08 00:45 UTC, merged

2022-11-20 12:27 UTC, AntonKanug commented
closes #21